### ISSUE TITLE
Is there any Support for ARcore Session?

### ISSUE THREAD

**Issue by ArunArtist** [glazunov/MyAwesomeFlashlight#1]
Hello Friend. This code is working fine on Android device and i am running on Android 11. the thing is its not working on a Unity scene consists of ARcore session where i find that its not currently supported by google when running under ARcore session for Augmented Reality. is there any possible way to run this script to work for ARcore session? meanwhile i tried Vuforia SDK for AR which natively working fine when accessing the Flashlight, but its not working when utilizing ARcore support for plane tracking.Thanking you for this plugin. best wishes.

**Comment by glazunov** [comment]
there's no support arcore, sorry
